# Generated by Django 2.2.3 on 2019-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.NullBooleanField(verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Goods_SPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.NullBooleanField(verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('detail', models.CharField(max_length=100, verbose_name='详情')),
            ],
            options={
                'db_table': 'goods_spu',
            },
        ),
        migrations.CreateModel(
            name='Goods_SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.NullBooleanField(verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('summary', models.TextField(max_length=200, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
                ('sales', models.PositiveIntegerField(verbose_name='销量')),
                ('category', models.ForeignKey(on_delete=None, to='goods.Category')),
                ('spu', models.ForeignKey(on_delete=None, to='goods.Goods_SPU')),
            ],
            options={
                'db_table': 'goods_sku',
            },
        ),
    ]
