# Generated by Django 2.2.3 on 2019-09-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_indexgoodsbanner_indexpromotionbanner_indextypegoodsbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods_sku',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goods_spu',
            options={'verbose_name': '商品SPU', 'verbose_name_plural': '商品SPU'},
        ),
        migrations.AlterModelTable(
            name='goods_sku',
            table='goods',
        ),
    ]
