# Generated by Django 2.2.3 on 2019-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190904_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_sku',
            name='image',
            field=models.ImageField(default=None, upload_to='goods', verbose_name='商品图片'),
            preserve_default=False,
        ),
    ]
